#Configurando cors de modo global, acesso a todos os recursos dos controllers e todas as operações
            #a partir das origins definidas abaixo
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br

#Configuração da integração com o banco de dados
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

#Configuração da documentação utilizando swagger
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true